backend:
  name: git-gateway

collections:
  - name: "site"
    label: "Site"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "homepage.yml"
        fields:
          - { label: "Title", name: "title", widget: "string" }
