backend:
  name: git-gateway
  identity_url: https://photosstudio.netlify.app/.netlify/identity
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "site"
    label: "Site"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "homepage.yml"
        fields:
          - { label: "Title", name: "title", widget: "string" }
